### ISSUE TITLE
不知道该如何进行

### ISSUE THREAD

**Issue by zhheo** [soxft/busuanzi-transfer#1]
首先停止旧项目，然后下载新项目。
然后安装go和redius吗
然后修改转换工具的config.yaml吗
修改之后运行go run main.go
这个原项目用docker安装的话，这个转换项目修改的是哪里，是当前文件夹下的dump.rdb吗，还是读取docker仓库内的redius
旧项目已经停止，还是需要旧版本运行时运行转换工具
还是转换工具放到指定路径呢

**Comment by zhheo** [comment]
对了这个是只能在运行busuanzi的服务器上运行是吧，还是可以在其他设备运行，然后将处理后的数据覆盖掉dump.rdb就行

**Comment by soxft** [comment]
已解决
